Repository GSG-G13/trakio, pull requests merged in 2023-07, with the labels that each got.

#52 Get project by user id from the api (in side bar)
  src/components/Sidebar/index.tsx
  src/interfaces/index.ts
  src/interfaces/projects.ts
Labels: awaiting-review, approved

#57 Tab bar component
  src/components/Layout/index.tsx
  src/components/Layout/layout.styled.tsx
  src/components/Sidebar/index.tsx
  src/components/TabBar/index.tsx
  src/components/index.ts
  src/interfaces/index.ts
  src/interfaces/projectDetails.ts
  src/interfaces/projects.ts
  src/pages/HomePage/index.tsx
  src/pages/Overview/index.tsx
Labels: approved

#50 Link project api
  src/components/ProjectsCard/Loader.tsx
  src/components/ProjectsCard/ProjectCard.tsx
  src/components/ProjectsCard/cards.styled.ts
  src/components/ProjectsCard/index.tsx
  src/components/Sidebar/index.tsx
  src/components/index.ts
  src/interfaces/index.ts
  src/interfaces/projectTasks.tsx
  src/interfaces/projects.ts
  src/interfaces/projects.tsx
  src/routes/index.tsx
Labels: approved

#64 Link delete account with the backend
  src/pages/AccountPage/index.tsx
Labels: approved

#66 Link task board with backend
  .eslintrc.cjs
  src/components/TaskCard/index.tsx
  src/interfaces/index.ts
  src/interfaces/section.ts
  src/pages/HomePage/index.tsx
  src/pages/TaskBoard/index.tsx
  src/routes/index.tsx
Labels: approved

#67 Link task calendar with backend
  package-lock.json
  package.json
  src/lotties/empty.json
  src/pages/Calendar/index.tsx
  src/pages/TaskBoard/TaskSkeleton.tsx
  src/pages/TaskBoard/index.tsx
Labels: approved

#68 Edit sidebar
  .eslintrc.cjs
  index.html
  public/assets/avatars/avatar_1.jpg
  public/assets/avatars/avatar_10.jpg
  public/assets/avatars/avatar_11.jpg
  public/assets/avatars/avatar_12.jpg
  public/assets/avatars/avatar_13.jpg
  public/assets/avatars/avatar_14.jpg
  public/assets/avatars/avatar_15.jpg
  public/assets/avatars/avatar_16.jpg
  public/assets/avatars/avatar_17.jpg
  public/assets/avatars/avatar_18.jpg
  public/assets/avatars/avatar_19.jpg
  public/assets/avatars/avatar_2.jpg
  public/assets/avatars/avatar_20.jpg
  public/assets/avatars/avatar_21.jpg
  public/assets/avatars/avatar_22.jpg
  public/assets/avatars/avatar_23.jpg
  public/assets/avatars/avatar_24.jpg
  public/assets/avatars/avatar_3.jpg
  public/assets/avatars/avatar_4.jpg
  public/assets/avatars/avatar_5.jpg
  public/assets/avatars/avatar_6.jpg
  public/assets/avatars/avatar_7.jpg
  public/assets/avatars/avatar_8.jpg
  public/assets/avatars/avatar_9.jpg
  public/assets/avatars/avatar_default.jpg
  public/assets/description.svg
  public/assets/iconsvg.svg
  public/assets/logo.svg
  public/assets/logoo.png
  public/assets/react.svg
  public/assets/todo.svg
  public/assets/welcome.svg
  public/vite.svg
  src/assets/logo.svg
  src/components/Common/ListItem.tsx
  src/components/Common/Logo.tsx
  src/components/Common/index.ts
  src/components/DescrioptionCard/index.tsx
  src/components/Login/LoginForm/index.tsx
  src/components/Login/index.tsx
  src/components/Sidebar/index.tsx
  src/components/Sidebar/sidebar.styled.tsx
  src/components/Signup/index.tsx
  src/components/UserCard/index.tsx
  src/components/UserCard/user.styled.tsx
  src/components/WelcomeCard/index.tsx
  src/constants/index.ts
  src/constants/nav.tsx
  src/fake.ts
  src/theme/index.ts
Labels: awaiting-review

#69 Link list page with the backend
  src/components/TaskTable/TaskRow.tsx
  src/components/TaskTable/TaskRowSkeleton.tsx
  src/components/TaskTable/TaskTable.tsx
Labels: approved

#72 Enhancing home page and project page
  src/components/DescrioptionCard/index.tsx
  src/components/ProjectsCard/ProjectCard.tsx
  src/components/ProjectsCard/cards.styled.ts
  src/components/WelcomeCard/index.tsx
  src/lotties/working.json
Labels: approved

#70 Add project to the database
  src/components/AccountInput/index.tsx
  src/components/AddProject/index.tsx
  src/helper/validation/schema.ts
  src/interfaces/index.ts
  src/interfaces/projects.tsx
Labels: approved

#74 Logout
  index.html
  src/components/Common/ListItem.tsx
  src/components/Login/LoginForm/index.tsx
  src/components/Sidebar/index.tsx
Labels: awaiting-review

#75 Overview page
  src/components/OverviewContent/Member.tsx
  src/components/OverviewContent/OverviewTaskCard.tsx
  src/components/OverviewContent/TitleAndDesc.tsx
  src/components/OverviewContent/index.ts
  src/components/OverviewContent/index.tsx
  src/components/OverviewContent/overview.styled.tsx
  src/components/Sidebar/index.tsx
  src/components/TabBar/index.tsx
  src/components/TaskCard/index.tsx
  src/components/TaskTable/TaskRow.tsx
  src/components/index.ts
  src/interfaces/index.ts
  src/interfaces/member.ts
  src/lotties/done.json
  src/lotties/inprogress.json
  src/lotties/presentation.json
  src/lotties/review.json
  src/lotties/todoSvg.json
  src/pages/Overview/index.tsx
Labels: approved

#79 Add user data by context
  src/UserContext/AuthContext.tsx
  src/UserContext/context.ts
  src/components/Login/LoginForm/index.tsx
  src/components/TabBar/index.tsx
  src/components/UserCard/index.tsx
  src/components/WelcomeCard/index.tsx
  src/interfaces/userData.ts
  src/main.tsx
Labels: approved

#56 Get data in account page
  package-lock.json
  package.json
  src/components/AccountInput/acount.styled.tsx
  src/components/AccountInput/index.tsx
  src/components/index.ts
  src/interfaces/userData.ts
  src/pages/AccountPage/index.tsx
Labels: approved

#80 Enhancing the function of user context
  package-lock.json
  src/UserContext/AuthContext.tsx
  src/components/Layout/index.tsx
  src/components/Login/index.tsx
  src/components/Signup/SignupForm/index.tsx
  src/components/Signup/index.tsx
Labels: awaiting-review

#78 Create update task components
  package-lock.json
  package.json
  src/components/TaskTable/TaskRow.tsx
  src/components/TaskTable/TaskTable.tsx
  src/components/UpdateTask/index.tsx
  src/components/UpdateTask/updateTask.styled.tsx
  src/constants/index.ts
  src/interfaces/task.ts
  src/pages/Overview/index.tsx
  src/pages/TaskBoard/index.tsx
Labels: approved

#84 Fixing a bug in overview page
  src/pages/Overview/index.tsx
Labels: approved

#86 Link delete project in project card
  src/components/ProjectsCard/ProjectCard.tsx
Labels: approved

#82 Create add members
  src/components/AddMember/index.tsx
  src/pages/Overview/index.tsx
Labels: awaiting-review

#89 Create errors page
  src/pages/Errors/clientError.tsx
  src/pages/Errors/error.tsx
  src/pages/Errors/serverError.tsx
  src/routes/index.tsx
Labels: awaiting-review

#76 Create add task
  package-lock.json
  package.json
  src/components/AddTask/addTask.styled.tsx
  src/components/AddTask/index.tsx
  src/components/FloatingButton/index.tsx
  src/components/index.ts
  src/fake.ts
  src/interfaces/initialValues.tsx
  src/pages/Overview/index.tsx
Labels: approved

#96 Add attachment feature
  .gitignore
  package-lock.json
  package.json
  src/components/TaskTable/TaskRow.tsx
  src/components/index.ts
  src/components/uploadModal/index.tsx
Labels: approved

#99 Fix styled in projects
  src/components/ProjectsCard/Loader.tsx
  src/components/ProjectsCard/Menu.tsx
  src/components/ProjectsCard/ProjectCard.tsx
  src/components/ProjectsCard/cards.styled.ts
  src/components/ProjectsCard/index.tsx
Labels: approved

#100 Download files from s3
  src/components/TabBar/index.tsx
  src/components/uploadModal/index.tsx
  src/interfaces/files.ts
  src/interfaces/index.ts
  src/pages/FilePage/index.tsx
  src/pages/index.ts
  src/routes/index.tsx
Labels: approved

#91 Link delete task with the backend
  .husky/commit-msg
  .husky/pre-commit
  package-lock.json
  package.json
  src/components/Alerts/dialog.styled.tsx
  src/components/Alerts/index.tsx
  src/components/ProjectsCard/ProjectCard.tsx
  src/components/StatisticsCard/index.tsx
  src/components/TaskTable/TaskRow.tsx
  src/components/index.ts
  src/pages/AccountPage/index.tsx
  src/pages/HomePage/index.tsx
Labels: approved

#103 Fixing husky
  .husky/commit-msg
  .husky/pre-commit
  package-lock.json
  package.json
  src/UserContext/context.ts
  src/components/AddMember/index.tsx
  src/components/AddProject/index.tsx
  src/components/AddTask/index.tsx
  src/components/AppBar/app.styled.tsx
  src/components/Layout/index.tsx
  src/components/ProjectsCard/Menu.tsx
  src/components/ProjectsCard/ProjectCard.tsx
  src/components/ProjectsCard/index.tsx
  src/components/Sidebar/index.tsx
  src/components/Signup/SignupForm/index.tsx
  src/components/TabBar/index.tsx
  src/components/TaskTable/TaskRow.tsx
  src/components/TaskTable/TaskTable.tsx
  src/components/UpdateTask/index.tsx
  src/components/WelcomeCard/index.tsx
  src/components/uploadModal/index.tsx
  src/interfaces/projectTasks.tsx
  src/lotties/noAttach.json
  src/pages/FilePage/index.tsx
  src/pages/Overview/index.tsx
Labels: awaiting-review

#108 Fix style
  .husky/commit-msg
  .husky/pre-commit
  package-lock.json
  package.json
  src/components/AddTask/addTask.styled.tsx
  src/components/AddTask/index.tsx
  src/components/TaskTable/TaskRow.tsx
  src/components/TaskTable/TaskTable.tsx
  src/components/UpdateTask/index.tsx
  src/components/uploadModal/index.tsx
  src/constants/index.ts
  src/interfaces/index.ts
  src/interfaces/priorities.ts
Labels: approved

#107 Link update project with the backend
  src/components/EditTask/index.tsx
  src/components/ProjectsCard/Menu.tsx
  src/components/ProjectsCard/ProjectCard.tsx
  src/components/UpdateProject/index.tsx
Labels: approved

#112 Enhancing the style of account page
  index.html
  src/UserContext/AuthContext.tsx
  src/components/AccountInput/acount.styled.tsx
  src/components/AccountInput/index.tsx
  src/components/AddMember/index.tsx
  src/components/AddProject/index.tsx
  src/components/AddTask/index.tsx
  src/components/Layout/index.tsx
  src/components/Login/LoginForm/index.tsx
  src/components/OverviewContent/Member.tsx
  src/components/OverviewContent/OverviewTaskCard.tsx
  src/components/OverviewContent/TitleAndDesc.tsx
  src/components/ProjectsCard/Menu.tsx
  src/components/ProjectsCard/ProjectCard.tsx
  src/components/Sidebar/index.tsx
  src/components/Signup/SignupForm/index.tsx
  src/components/Signup/index.tsx
  src/components/StatisticsCard/index.tsx
  src/components/TabBar/index.tsx
  src/components/TaskTable/TaskRow.tsx
  src/components/TaskTable/TaskTable.tsx
  src/components/UpdateProject/index.tsx
  src/components/UpdateTask/index.tsx
  src/components/index.ts
  src/components/uploadModal/index.tsx
  src/constants/endpoints.ts
  src/lotties/profile.json
  src/pages/AccountPage/index.tsx
  src/pages/Calendar/index.tsx
  src/pages/FilePage/index.tsx
  src/pages/Overview/index.tsx
  src/pages/TaskBoard/index.tsx
  vite.config.ts
Labels: approved

#110 Create readme file
  README.md
  example.env
Labels: approved

#116 Error with uploading files
  src/components/ProjectsCard/cards.styled.ts
  src/pages/FilePage/index.tsx
  vite.config.ts
Labels: approved

#118 GitHub action workflow
  .github/workflows/deploy.yml
Labels: awaiting-review

#119 Update index.ts
  src/components/index.ts
Labels: done
