Repository GSG-G13/trakio, pull requests merged in 2023-06, with the labels that each got.

#2 Create react setup
  .commitlintrc.cjs
  .eslintrc.cjs
  .gitignore
  .husky/commit-msg
  .husky/pre-commit
  .vscode/settings.json
  index.html
  package-lock.json
  package.json
  public/vite.svg
  src/assets/react.svg
  src/components/index.ts
  src/hooks/index.ts
  src/index.css
  src/layout/Layout.tsx
  src/layout/index.ts
  src/main.tsx
  src/pages/index.ts
  src/routes/index.ts
  src/theme/index.ts
  src/utils/index.ts
  src/vite-env.d.ts
  tsconfig.json
  tsconfig.node.json
  vite.config.ts
Labels: approved

#6 Layout Components
  .eslintrc.cjs
  index.html
  package-lock.json
  src/assets/iconsvg.svg
  src/assets/logo.svg
  src/assets/welcome.svg
  src/components/AppBar/app.styled.tsx
  src/components/AppBar/index.tsx
  src/components/Layout/index.tsx
  src/components/Layout/layout.styled.tsx
  src/components/Sidebar/index.tsx
  src/components/Sidebar/sidebar.styled.tsx
  src/components/index.ts
  src/constants/index.ts
  src/index.css
  src/main.tsx
  src/pages/HomePage/HomePage.tsx
  src/pages/index.ts
  src/theme/index.ts
Labels: approved

#9 Create the table of tasks component
  package-lock.json
  package.json
  src/components/Layout/index.tsx
  src/components/TaskTable/TaskRow.tsx
  src/components/TaskTable/TaskTable.tsx
  src/components/index.ts
  src/interfaces/index.ts
  src/interfaces/task.ts
  src/pages/HomePage/HomePage.tsx
  src/theme/index.ts
Labels: approved

#14 Welcome card component
  src/components/AppBar/index.tsx
  src/components/Layout/index.tsx
  src/components/WelcomeCard/card.styled.tsx
  src/components/WelcomeCard/index.tsx
Labels: approved

#16 Refactor statistics card components
  src/components/Layout/index.tsx
  src/components/StatisticsCard/index.tsx
  src/components/StatisticsCard/statistics.styed.tsx
Labels: awaiting-review

#5 Create projects card
  package.json
  src/components/Layout/index.tsx
  src/components/ProjectsCard/cards.styled.ts
  src/components/ProjectsCard/index.tsx
  src/components/index.ts
  src/theme/index.ts
Labels: approved

#18 Description card
  src/assets/description.svg
  src/components/DescrioptionCard/description.styled.tsx
  src/components/DescrioptionCard/index.tsx
  src/components/Layout/index.tsx
Labels: approved

#13 Create the task card component
  src/components/TaskCard/index.tsx
  src/components/index.ts
  src/interfaces/task.ts
Labels: approved

#24 Create login page and client side validation
  package-lock.json
  package.json
  src/assets/todo.svg
  src/components/Common/Button.tsx
  src/components/Common/Input.tsx
  src/components/Common/Text.tsx
  src/components/Login/LoginForm/index.tsx
  src/components/Login/LoginForm/loginForm.styled.tsx
  src/components/Login/index.tsx
  src/components/Login/login.styled.tsx
  src/components/index.ts
  src/helper/validation/yupSchema.ts
  src/main.tsx
  src/pages/LoginPage/LoginPage.tsx
  src/pages/index.ts
Labels: approved

#25 Create task board
  src/components/TaskCard/index.tsx
  src/fake.ts
  src/interfaces/task.ts
  src/pages/TaskBoard/index.tsx
Labels: done

#23 Create account page
  src/components/AccountInput/acount.styled.tsx
  src/components/AccountInput/index.tsx
  src/components/AddProject/index.tsx
  src/components/Layout/index.tsx
  src/components/index.ts
  src/interfaces/userData.ts
  src/main.tsx
  src/pages/AccountPage/index.tsx
  src/pages/index.ts
Labels: awaiting-review

#29 Charts component
  package-lock.json
  package.json
  src/components/Charts/BarChart.tsx
  src/components/Charts/LineChart.tsx
  src/components/Charts/charts.styled.tsx
  src/components/Charts/index.tsx
  src/components/Layout/index.tsx
  src/components/ProjectsCard/cards.styled.ts
  src/components/ProjectsCard/index.tsx
  src/components/Sidebar/index.tsx
  src/components/TaskCard/index.tsx
  src/components/WelcomeCard/card.styled.tsx
  src/components/WelcomeCard/index.tsx
  src/components/index.ts
  src/pages/HomePage/HomePage.tsx
Labels: approved

#27 Create router
  src/components/Layout/index.tsx
  src/components/Sidebar/index.tsx
  src/components/index.ts
  src/layout/Layout.tsx
  src/layout/index.ts
  src/main.tsx
  src/pages/HomePage/HomePage.tsx
  src/pages/HomePage/index.tsx
  src/pages/LoginPage/index.tsx
  src/pages/index.ts
  src/routes/index.ts
  src/routes/index.tsx
Labels: approved

#33 Create the calendar page
  package-lock.json
  package.json
  src/pages/Calendar/index.tsx
  src/pages/index.ts
  src/routes/index.tsx
Labels: awaiting-review

#41 Link api and create Alerts
  src/components/Alerts/index.tsx
  src/components/Login/LoginForm/index.tsx
  src/components/index.ts
  vite.config.ts
Labels: approved

#37 Create signup page
  src/components/EditTask/index.tsx
  src/components/Login/LoginForm/index.tsx
  src/components/Login/LoginForm/loginForm.styled.tsx
  src/components/Signup/SignupForm/index.tsx
  src/components/Signup/SignupForm/signupForm.tsx
  src/components/Signup/index.tsx
  src/components/Signup/signup.styled.tsx
  src/helper/validation/schema.ts
  src/helper/validation/yupSchema.ts
  src/pages/SigupPage/SignupPage.tsx
  src/pages/index.ts
  src/routes/index.tsx
Labels: awaiting-review

#31 Create add project
  package-lock.json
  src/components/AccountInput/index.tsx
  src/components/AddProject/addProject.styled.tsx
  src/components/AddProject/index.tsx
  src/components/ProjectsCard/index.tsx
  src/components/Sidebar/index.tsx
  src/components/WelcomeCard/index.tsx
  src/routes/index.tsx
Labels: approved

#38 Overview page
  src/components/OverviewContent/index.tsx
  src/components/OverviewContent/overview.styled.tsx
  src/components/index.ts
  src/pages/Overview/index.tsx
  src/pages/index.ts
  src/routes/index.tsx
Labels: approved

#44 Link signup page with the backend
  src/components/Signup/SignupForm/index.tsx
Labels: approved

#48 Get statistics from the backend
  src/components/StatisticsCard/index.tsx
  src/components/TaskCard/index.tsx
  src/interfaces/index.ts
  vite.config.ts
Labels: awaiting-review

#49 Update router
  src/components/Sidebar/index.tsx
  src/routes/index.tsx
Labels: awaiting-review
